version: '2'
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    container_name: container-name
    build: .
    ports:
      - 6000:9000
    volumes:
     - .:/app
     - /app/vendor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dbname@postgres/dbname
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pw
    ports:
      - 3306:5432
    volumes:
      - ../PostgresData/data:/var/lib/postgresql/data
  redis:
    container_name: container-name
    build: ./Redis/
    ports:
      - 6003:6379
    volumes:
      - ../RedisData/data:/data
    command: redis-server --appendonly yes
    depends_on:
      - api
